In [1]:
import torch

In [9]:
torch.manual_seed(0)
a = torch.randn(2, 3, 4)
a

tensor([[[-1.1258, -1.1524, -0.2506, -0.4339],
         [ 0.8487,  0.6920, -0.3160, -2.1152],
         [ 0.4681, -0.1577,  1.4437,  0.2660]],

        [[ 0.1665,  0.8744, -0.1435, -0.1116],
         [ 0.9318,  1.2590,  2.0050,  0.0537],
         [ 0.6181, -0.4128, -0.8411, -2.3160]]])

In [10]:
b = torch.randn(4, 1)

In [11]:
torch.einsum('ijk,kl->ijl', a, b)

tensor([[[-2.6671],
         [-0.6137],
         [ 1.5066]],

        [[ 1.1139],
         [ 4.1048],
         [-2.9573]]])

In [12]:
torch.matmul(a, b)

tensor([[[-2.6671],
         [-0.6137],
         [ 1.5066]],

        [[ 1.1139],
         [ 4.1048],
         [-2.9573]]])

In [13]:
for i in a:
    print(torch.mm(i, b))

tensor([[-2.6671],
        [-0.6137],
        [ 1.5066]])
tensor([[ 1.1139],
        [ 4.1048],
        [-2.9573]])
