In [2]:
import os
from main import eval_runs
from params import PARAMS

In [5]:
model_names = sorted(os.listdir('./output'))
random_seeds = PARAMS['RANDOM_SEEDS']
print(random_seeds)
final_results = eval_runs(model_names, random_seeds)
for k, v in final_results.items():
    print(k)
    print(v['accuracy'])

[688933, 890203, 517391, 195645, 705223]
imagine_cnn
[0.28923611111111114, 0.01112195651253262]
imagine_fcn
[0.29097222222222224, 0.004735479755897871]
imagine_gcn
[0.2756944444444444, 0.006892164319888613]
imagine_gcn_auto
[0.3232638888888889, 0.013949520435139341]
imagine_rnn
[0.29375, 0.006440012844094235]


In [4]:
model_names = sorted(os.listdir('./output'))
random_seeds = [0, 1, 2, 3, 4]
print(random_seeds)
final_results = eval_runs(model_names, random_seeds)
for k, v in final_results.items():
    print(k)
    print(v['accuracy'])

[0, 1, 2, 3, 4]
imagine_cnn
[0.29965277777777777, 0.014087126927153326]
imagine_fcn
[0.29375, 0.004308914460413491]
imagine_gcn
[0.27118055555555554, 0.004836245929577821]
imagine_gcn_auto
[0.32222222222222224, 0.01185650769372491]
imagine_rnn
[0.2940972222222222, 0.012548132638606001]


In [3]:
model_names = sorted(os.listdir('./output'))
random_seeds = PARAMS['RANDOM_SEEDS']
print(random_seeds)
final_results = eval_runs(model_names, random_seeds)
for k, v in final_results.items():
    print(k)
    print(v['accuracy'])

[688933, 890203, 517391, 195645, 705223]
imagine_cnn
[0.28923611111111114, 0.01112195651253262]
imagine_fcn
[0.259375, 0.0043368041655544535]
imagine_gcn
[0.2756944444444444, 0.006892164319888613]
imagine_gcn_auto
[0.3232638888888889, 0.013949520435139341]
imagine_rnn
[0.2833333333333333, 0.011484607922598077]


In [4]:
model_names = sorted(os.listdir('./output'))
random_seeds = [0, 1, 2, 3, 4]
print(random_seeds)
final_results = eval_runs(model_names, random_seeds)
for k, v in final_results.items():
    print(k)
    print(v['accuracy'])

[0, 1, 2, 3, 4]
imagine_cnn
[0.29965277777777777, 0.014087126927153326]
imagine_fcn
[0.29375, 0.004308914460413491]
imagine_gcn
[0.27118055555555554, 0.004836245929577821]
imagine_gcn_auto
[0.32222222222222224, 0.01185650769372491]
imagine_rnn
[0.2940972222222222, 0.012548132638606001]


In [2]:
import torch
from torch import nn

In [3]:
node_embeddings = nn.Parameter(torch.randn(64, 64), requires_grad=True)

In [5]:
print(node_embeddings)

Parameter containing:
tensor([[-0.9152,  0.4050,  0.0131,  ...,  0.7229, -2.2499,  0.2592],
        [ 0.5440,  0.9877,  1.3060,  ..., -0.4470, -0.1944, -0.9888],
        [ 0.6952, -1.2124, -0.3913,  ...,  0.1852, -0.4294,  1.5586],
        ...,
        [-0.2348, -2.5868, -0.1821,  ..., -0.6892, -1.2207,  1.4488],
        [ 0.4342,  0.1364,  0.2026,  ..., -0.6974, -0.5861, -0.5135],
        [-0.3321, -0.3501, -0.4647,  ..., -0.5017, -0.3689,  0.4645]],
       requires_grad=True)


In [6]:
node_embeddings.T

tensor([[-0.9152,  0.5440,  0.6952,  ..., -0.2348,  0.4342, -0.3321],
        [ 0.4050,  0.9877, -1.2124,  ..., -2.5868,  0.1364, -0.3501],
        [ 0.0131,  1.3060, -0.3913,  ..., -0.1821,  0.2026, -0.4647],
        ...,
        [ 0.7229, -0.4470,  0.1852,  ..., -0.6892, -0.6974, -0.5017],
        [-2.2499, -0.1944, -0.4294,  ..., -1.2207, -0.5861, -0.3689],
        [ 0.2592, -0.9888,  1.5586,  ...,  1.4488, -0.5135,  0.4645]],
       grad_fn=<PermuteBackward0>)

In [7]:
sym = torch.mm(node_embeddings, node_embeddings.T)

In [8]:
sym

tensor([[ 59.5107,  -1.1300,  -6.2444,  ...,  12.8019,  -7.1642,  -0.3903],
        [ -1.1300,  65.5720,   4.0584,  ...,   3.3002, -17.4122,  -2.9555],
        [ -6.2444,   4.0584,  64.2707,  ...,   7.4791,  -8.0751,   3.3873],
        ...,
        [ 12.8019,   3.3002,   7.4791,  ...,  80.2636,  -7.7915,  -0.7493],
        [ -7.1642, -17.4122,  -8.0751,  ...,  -7.7915,  63.5058,  11.1530],
        [ -0.3903,  -2.9555,   3.3873,  ...,  -0.7493,  11.1530,  47.2150]],
       grad_fn=<MmBackward0>)

In [9]:
torch.relu(sym)

tensor([[59.5107,  0.0000,  0.0000,  ..., 12.8019,  0.0000,  0.0000],
        [ 0.0000, 65.5720,  4.0584,  ...,  3.3002,  0.0000,  0.0000],
        [ 0.0000,  4.0584, 64.2707,  ...,  7.4791,  0.0000,  3.3873],
        ...,
        [12.8019,  3.3002,  7.4791,  ..., 80.2636,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000, 63.5058, 11.1530],
        [ 0.0000,  0.0000,  3.3873,  ...,  0.0000, 11.1530, 47.2150]],
       grad_fn=<ReluBackward0>)

In [10]:
torch.sigmoid(torch.relu(sym))

tensor([[1.0000, 0.5000, 0.5000,  ..., 1.0000, 0.5000, 0.5000],
        [0.5000, 1.0000, 0.9830,  ..., 0.9644, 0.5000, 0.5000],
        [0.5000, 0.9830, 1.0000,  ..., 0.9994, 0.5000, 0.9673],
        ...,
        [1.0000, 0.9644, 0.9994,  ..., 1.0000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000,  ..., 0.5000, 1.0000, 1.0000],
        [0.5000, 0.5000, 0.9673,  ..., 0.5000, 1.0000, 1.0000]],
       grad_fn=<SigmoidBackward0>)

In [12]:
torch.softmax(torch.relu(sym), dim=1)

tensor([[1.0000e+00, 1.4283e-26, 1.4283e-26,  ..., 5.1836e-21, 1.4283e-26,
         1.4283e-26],
        [3.3299e-29, 1.0000e+00, 1.9275e-27,  ..., 9.0301e-28, 3.3299e-29,
         3.3299e-29],
        [1.2235e-28, 7.0820e-27, 1.0000e+00,  ..., 2.1663e-25, 1.2235e-28,
         3.6199e-27],
        ...,
        [5.0321e-30, 3.7602e-34, 2.4551e-32,  ..., 1.0000e+00, 1.3866e-35,
         1.3866e-35],
        [2.6290e-28, 2.6290e-28, 2.6290e-28,  ..., 2.6290e-28, 1.0000e+00,
         1.8344e-23],
        [3.1245e-21, 3.1245e-21, 9.2444e-20,  ..., 3.1245e-21, 2.1801e-16,
         1.0000e+00]], grad_fn=<SoftmaxBackward0>)